### ISSUE TITLE
[FEATURE] A map-based theming API

### ISSUE THREAD

**Issue by MatteuSan** [dev-protocol/hashi-web#84]
### Detailed description

Add a map-based theming API to Hashi.

### Context

This lets developers import pre-made themes (either made internally, or by the community) into Hashi.

### Possible implementation

Have a `$theme` parameter in the `with ()` keyword that takes in a map-based theme. We're adding a new concept to the internal API called "Theme Prioritization", wherein the `$theme` parameter will always take the first priority. Meaning, whenever you override a single-purpose parameter, say `$accent`, the `'accent'` key inside the `$theme` map will be the first to be used as it's on the top of the priority hierarchy.

```scss
// main.scss
@use 'node_modules/@example-organization/haru'; // the map-based theme in a package

@use 'node_modules/@devprotocol/hashi' with (
  $theme: haru.$global-theme
);
@use 'node_modules/@devprotocol/hashi/hs-button' with (
  $theme: haru.$button-theme
);

@include hashi.init {
  @include hs-button.render();
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
